User.find_or_create_by(username: "boos")
User.find_or_create_by(username: "fill")
User.find_or_create_by(username: "teddy")
User.find_or_create_by(username: "wayne")
User.find_or_create_by(username: "roni")
User.find_or_create_by(username: "cari")
User.find_or_create_by(username: "elaina")
User.find_or_create_by(username: "herman")
User.find_or_create_by(username: "josh")
User.find_or_create_by(username: "whosale")

Friendship.find_or_create_by(user_id:2,friend_id:2)
Friendship.find_or_create_by(user_id:1,friend_id:3)
Friendship.find_or_create_by(user_id:1,friend_id:4)
Friendship.find_or_create_by(user_id:1,friend_id:5)
Friendship.find_or_create_by(user_id:1,friend_id:6)
Friendship.find_or_create_by(user_id:1,friend_id:7)
Friendship.find_or_create_by(user_id:1,friend_id:8)
Friendship.find_or_create_by(user_id:1,friend_id:9)
Friendship.find_or_create_by(user_id:1,friend_id:10)

Friendship.find_or_create_by(user_id:2,friend_id:1)
Friendship.find_or_create_by(user_id:2,friend_id:3)
Friendship.find_or_create_by(user_id:2,friend_id:4)
Friendship.find_or_create_by(user_id:2,friend_id:5)
Friendship.find_or_create_by(user_id:2,friend_id:6)
Friendship.find_or_create_by(user_id:2,friend_id:7)
Friendship.find_or_create_by(user_id:2,friend_id:8)
Friendship.find_or_create_by(user_id:2,friend_id:9)
Friendship.find_or_create_by(user_id:2,friend_id:10)
